name: Test Hugo Build

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Test Build
        run: |
          cd 000058-SessionManager
          hugo --minify
          echo "Build successful!" 